version: '3'

networks:
  xy_net:
    external: true

services:
  xy:
    container_name: "${XY_CONTAINER}"
    env_file: [ "${ENV_FILE}" ]
    image: "${XY_IMAGE}"
    networks: [ xy_net ]
    ports: [ "80:${XY_PORT}" ]
    tmpfs: [ /tmp ]
    volumes:
      - ./server:${XY_APP_DIR}/server:rw
      - ./test:${XY_APP_DIR}/test:rw
      - ./coverage:${XY_APP_DIR}/coverage:rw
    #read_only: true
