version: '3'

networks:
  xy_net:
    external: true

services:
  xy:
    networks: [ xy_net ]
    image: ${XY_IMAGE}
    container_name: ${XY_CONTAINER}
    env_file: [ "${ENV_FILE}" ]
    ports: ["80:${XY_PORT}"]
    stop_signal: SIGINT
    tmpfs: [ /tmp ]


