version: '3'

networks:
  xy_net:
    external: true

services:
  xy-{NAME}:  # See scripts/test/lib.py server_up()
    container_name: "${XY_CONTAINER}"
    env_file: [ "${ENV_FILE}" ]
    image: "${XY_IMAGE}"
    networks: [ xy_net ]
    ports: [ "${XY_APP_PORT}:${XY_CONTAINER_PORT}" ]
    tmpfs: [ /tmp ]
    volumes:
      - ./server:${XY_APP_DIR}/server:ro
      - ./test:${XY_APP_DIR}/test:ro
      - ./coverage:${XY_APP_DIR}/coverage:rw
    read_only: true
