version: '3'

networks:
  xy_net:
    external: true

services:
  xy:
    container_name: ${XY_CONTAINER}
    env_file: [ "${ENV_FILE}" ]
    image: ${XY_IMAGE}
    networks: [ xy_net ]
    ports: ["80:${XY_PORT}"]
    stop_signal: SIGINT
    tmpfs: [ /tmp ]
    volumes: [ "./test/system/.coveragerc:/${XY_DIR}/test/system/.coveragerc" ]


