version: '3'

networks:
  xy_net:
    external: true

services:
  xy:
    container_name: "${XY_CONTAINER}"
    env_file: [ "${ENV_FILE}" ]
    image: "${XY_IMAGE}"
    networks: [ xy_net ]
    ports: [ "80:${XY_PORT}" ]
    tmpfs: [ /tmp ]
    volumes: [ ".:${XY_APP_DIR}" ]

# The volume-mount is required so that
# html coverage reports written inside a container
# are available after the container has exited.