version: '3'

networks:
  xy_net:
    external: true

services:
  xy-{NAME}:  # See scripts/test/lib.py bring_server_up()
    container_name: "${XY_CONTAINER_NAME}"
    env_file: [ "${ENV_FILE}" ]
    image: "${XY_IMAGE_NAME}"
    networks: [ xy_net ]
    ports: [ "${XY_HOST_PORT}:${XY_CONTAINER_PORT}" ]
    read_only: true
    tmpfs: [ /tmp ]
    user: xy
    volumes:
      - ./source:${XY_CONTAINER_ROOT_DIR}/source:ro
      - ./test:${XY_CONTAINER_ROOT_DIR}/test:ro
