version: '3'

networks:
  xy_net:
    external: true

services:
  xy:
    container_name: "${XY_CONTAINER}"
    env_file: [ "${ENV_FILE}" ]
    image: "${XY_IMAGE}"
    networks: [ xy_net ]
    ports: [ "80:${XY_PORT}" ]
    tmpfs: [ /tmp ]
    volumes:
      - ./server:${XY_APP_DIR}/server
      - ./test:${XY_APP_DIR}/test
      - ./coverage:${XY_APP_DIR}/coverage

# The volume-mount is required so that
# html coverage reports written inside a container
# are available after the container has exited.