version: '3'

networks:
  xy_net:
    external: true

services:
  xy-{NAME}:  # See scripts/test/lib.py server_up()
    container_name: "${XY_CONTAINER_NAME}"
    env_file: [ "${ENV_FILE}" ]
    image: "${XY_IMAGE_NAME}"
    networks: [ xy_net ]
    ports: [ "${XY_HOST_PORT}:${XY_CONTAINER_PORT}" ]
    tmpfs:
      - /tmp
      - ${XY_CONTAINER_DIR}/coverage
    volumes:
      - ./server:${XY_CONTAINER_DIR}/server:ro
      - ./test:${XY_CONTAINER_DIR}/test:ro
    read_only: true
